from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum

class SensorType(str, Enum):
    TEMPERATURE = "temperature"
    PRESSURE = "pressure"
    VIBRATION = "vibration"
    FLOW_RATE = "flow_rate"
    VOLTAGE = "voltage"

class TelemetryStatus(str, Enum):
    NOMINAL = "nominal"
    WARNING = "warning"
    CRITICAL = "critical"

class SensorTelemetry(BaseModel):
    """
    API Contract for a Sensor Telemetry Packet
    Routed via Redis Pub/Sub from the simulator to the backend.
    """
    sensor_id: str = Field(..., description="Unique identifier for the sensor")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Time of the sensor reading in UTC")
    sensor_type: SensorType = Field(..., description="Type of physical measurement")
    value: float = Field(..., description="Current sensor reading value")
    unit: str = Field(..., description="Unit of measurement (e.g., Celsius, PSI, RPM, V)")
    status: TelemetryStatus = Field(
        default=TelemetryStatus.NOMINAL, 
        description="Local boundary status evaluation (Nominal, Warning, Critical)"
    )
    metadata: Optional[Dict[str, Any]] = Field(
        default_factory=dict, 
        description="Additional context (e.g., location, firmware_version)"
    )


class IncidentSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

class AIIncidentReport(BaseModel):
    """
    API Contract for an AI Incident Report Packet
    Generated by the LangGraph multi-agent system after correlating anomalies to prevent alarm fatigue.
    """
    incident_id: str = Field(..., description="Unique UUID for the generated incident")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Time the report was compiled in UTC")
    severity: IncidentSeverity = Field(..., description="Assessed holistic severity of the incident")
    title: str = Field(..., description="Short, human-readable, actionable title (e.g., 'Impending Pump B Failure')")
    summary: str = Field(..., description="AI-generated executive summary of the situation")
    root_cause_analysis: str = Field(..., description="Detailed explanation of the correlated sensor data and the likely physical root cause")
    correlated_sensors: List[str] = Field(..., description="List of sensor_ids that contributed to identifying this incident")
    recommended_actions: List[str] = Field(..., description="Ordered list of step-by-step mitigation actions for the operator")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="AI's confidence probability in this assessment (0.0 to 1.0)")
